### PR TITLE
added snap/snapcraft support

### PR DESCRIPTION
**Pull request by simos**
Snaps are [installation packages that run in Ubuntu and other Linux distributions](https://snapcraft.io/).
I added here the configuration file to package "amass" using the "snapcraft" tool.
Then, you can upload the package to the snap package repository so that anyone can install from there. 

I have done this for a package name "amass-simosx" (the name "amass" is still available, and if you are OK with these, you can register it and upload yourself there). Here is how it looks:

# How to use (can try this now)
Search for the package name
```
$ snap find amass
Name          Version  Developer  Notes  Summary
amass-simosx  1.0.0    simosx     -      Subdomain enumeration

```
Install the package
```
$ sudo snap install amass-simosx
amass-simosx 1.0.0 from 'simosx' installed

```
Run `amass`. When you register the package name `amass`, the executable will be just `amass`.
```
$ amass-simosx.amass
...
```

# How to add your official amass snap to the Store

1. Install the tool `snapcraft`. See https://snapcraft.io/
2. In the `amass/` source directory, run `snapcraft`. The tool will find the instructions in snap/snapcraft.yaml, compile, build and package into a *.snap installation file.
3. Run 'snapcraft login' to login to the Store. If you do not have an account, create one at https://login.ubuntu.com/
4. Register the name 'amass' with:  snapcraft register amass
5. Upload the generated .snap file (step 2) to the Store, with `snapcraft push amass_1.0.0_amd64.snap`
6. Release the package to the Store with: `snapcraft release amass 1 stable`

I am OK to unrelease the `amass-simosx` once you release the official package.

### CODE REVIEW

**Comment by caffix** [comment]
I have registered the snap as amass. Please feel free to remove the previously registered version.

**Comment by simos** [comment]
Thanks! I just removed the `amass-simosx` snap.

**Comment by caffix** [comment]
When I attempted to execute the amass (symbolic link) installed by the snap, it told me that the command wrapper could not find the amass binary. Can you suggest a way to fix this issue? Thanks.

**Comment by simos** [comment]
You can get into a shell that has the `amass` permissions with the following command.
Then, you can look into 

```
$ snap run --shell amass
To run a command as administrator (user "root"), use "sudo <command>".
See "man sudo_root" for details.

$ cd /snap/amass/current/
$ ls -l
total 1
drwxr-xr-x 2 root root 43 Mar 13 06:51 bin
-rwxr-xr-x 1 root root 28 Mar 13 06:51 command-amass.wrapper
drwxr-xr-x 3 root root 43 Mar 13 06:51 meta
$ ls -l bin/
total 17710
-rwxr-xr-x 1 root root 9054713 Mar 13 06:51 amass
-rwxr-xr-x 1 root root 9079714 Mar 13 06:51 maltego
$ 
```

What is happening, is that `command-amass.wrapper` should be adapted to find the `amass` executable in the bin/ subdirectory, not in /snap/amass/current/.
To do so, make the following change in snapcraft.yaml:

```
apps:
  amass:
    command: bin/amass
    plugs: [home, network, removable-media]
```

**Comment by caffix** [comment]
Thanks again!

**Pull request merged**
