### PR TITLE
reduced image size

### PR DESCRIPTION
**Pull request by fopina**
Using multi-stage and `FROM scratch` to reduce image size (considerably)
```
original       latest               96887cf4ab24        4 minutes ago       927MB
new            latest               388223142ec6        10 minutes ago      13.1MB
```

### CODE REVIEW

**Comment by petermbenjamin** [comment]
@fopina - the CONTRIBUTING.md instructions are to fork and submit PRs against the `develop` branch, not master.

**Comment by caffix** [comment]
Would you two please create one set of enhancements to the Docker files and submit it to the develop branch? Thank you.

**Comment by petermbenjamin** [comment]
PR #63 includes a lot more optimizations to the Dockerfile than just image size :)

**Comment by fopina** [comment]
Glad to help anyway :)

**Pull request closed without merging**
